// English interface strings, keyed by the French source text used in the
// components. A missing entry simply shows the French text.
export default {
  // ---- shared
  "Annuler": "Cancel",
  "Enregistrer": "Save",
  "Fermer": "Close",
  "Confirmer": "Confirm",
  "Supprimer": "Delete",
  "Réessayer": "Try again",
  "Ajouter": "Add",
  "Retirer": "Remove",
  "Oui": "Yes",
  "Non": "No",
  "Aucun": "None",
  "Tous": "All",
  "Tout": "All",
  "Chargement…": "Loading…",
  "En cours…": "In progress…",
  "vous": "you",
  "Statut": "Status",
  "Urgence": "Urgency",
  "Sentiment": "Sentiment",
  "Département": "Department",
  "Type": "Type",
  "Motif": "Issue",
  "Objet": "Subject",
  "Résumé": "Summary",
  "Ticket": "Ticket",
  "Date": "Date",
  "Message": "Message",
  "Client": "Client",
  "Identifiant": "Username",
  "Mot de passe": "Password",
  "E-mail": "E-mail",

  // ---- states
  "Ouvert": "Open",
  "En cours": "In progress",
  "Résolu": "Resolved",
  "Haute": "High",
  "Moyenne": "Medium",
  "Basse": "Low",
  "Négatif": "Negative",
  "Neutre": "Neutral",
  "Positif": "Positive",
  "Réclamation": "Complaint",
  "Demande": "Request",
  "Employé": "Employee",
  "Administrateur": "Administrator",
  "Clients": "Clients",
  "Employés": "Employees",
  "Administrateurs": "Administrators",
  "Assistant client et suivi de ses propres tickets": "Client assistant and tracking of their own tickets",
  "Tableau de bord et analyse des causes racines": "Dashboard and root cause analysis",
  "Accès complet, paramètres et gestion des comptes": "Full access, settings and account management",
  "Hybride (ML + LLM)": "Hybrid (ML + LLM)",
  "LLM seul": "LLM only",
  "ML seul": "ML only",
  "Repli local (ML)": "Local fallback (ML)",
  "Tri des demandes": "Request triage",

  // ---- navigation & shell
  "Assistant": "Assistant",
  "Tableau de bord": "Dashboard",
  "Causes racines": "Root causes",
  "Paramètres": "Settings",
  "ECCBC Service Client": "ECCBC Customer Desk",
  "Navigation principale": "Main navigation",
  "Changer de thème": "Switch theme",
  "Thème clair": "Light theme",
  "Thème sombre": "Dark theme",
  "Passer au thème clair": "Switch to light theme",
  "Passer au thème sombre": "Switch to dark theme",
  "Déplier le menu": "Expand menu",
  "Réduire le menu": "Collapse menu",
  "Mon compte": "My account",
  "Changer le mot de passe": "Change password",
  "Se déconnecter": "Sign out",
  "Mot de passe mis à jour.": "Password updated.",
  "Mot de passe actuel": "Current password",
  "Nouveau mot de passe": "New password",
  "8 caractères minimum.": "At least 8 characters.",
  "Votre session a expiré. Veuillez vous reconnecter.": "Your session has expired. Please sign in again.",
  "Serveur injoignable. Vérifiez votre connexion puis réessayez.": "Server unreachable. Check your connection and try again.",

  // ---- login
  "Connexion": "Sign in",
  "Accédez à votre espace avec vos identifiants.": "Access your workspace with your credentials.",
  "Masquer le mot de passe": "Hide password",
  "Afficher le mot de passe": "Show password",
  "Se connecter": "Sign in",
  "Service client": "Customer desk",
  "Chaque demande,": "Every request,",
  "comprise, routée": "understood, routed",
  "et suivie.": "and tracked.",
  "Questions, commandes et réclamations, en français, en anglais ou en darija : un seul point d'entrée pour les clients et les équipes.":
    "Questions, orders and complaints, in French, English or Darija: one entry point for clients and teams.",
  "Accès démo": "Demo access",
  "Admin": "Admin",
  "Analyse des causes racines": "Root cause analysis",

  // ---- assistant
  "Assistant ECCBC": "ECCBC Assistant",
  "Nouvelle conversation": "New conversation",
  "Mes tickets": "My tickets",
  "Bonjour {name},": "Hello {name},",
  "Bonjour {name}": "Hello {name}",
  "Bonjour,": "Hello,",
  "que pouvons-nous faire pour vous ?": "how can we help you?",
  "Posez une question, faites une demande de commande ou de livraison, ou signalez un problème. Vous pouvez écrire en français, en anglais ou en darija.":
    "Ask a question, make an order or delivery request, or report a problem. You can write in French, English or Darija.",
  "Signaler un problème": "Report a problem",
  "Passer une commande": "Place an order",
  "Poser une question": "Ask a question",
  "Écrire en darija": "Write in Darija",
  "Analyse de votre message…": "Reading your message…",
  "Écrivez votre message…": "Write your message…",
  "Votre message": "Your message",
  "Envoyer": "Send",
  "Entrée pour envoyer, Maj + Entrée pour un saut de ligne": "Enter to send, Shift + Enter for a new line",
  "Les réponses sont générées automatiquement puis suivies par nos équipes.":
    "Replies are generated automatically, then followed up by our teams.",
  "Votre message n'a pas pu être traité.": "Your message could not be processed.",
  "Réclamation enregistrée": "Complaint recorded",
  "Demande enregistrée": "Request recorded",
  "Copier la référence {id}": "Copy reference {id}",
  "Service en charge": "Team in charge",
  "Priorité": "Priority",
  "Conservez cette référence pour le suivi.": "Keep this reference for follow-up.",
  "{n} ticket enregistré": "{n} ticket recorded",
  "{n} tickets enregistrés": "{n} tickets recorded",
  "Aucun ticket pour le moment": "No tickets yet",
  "Vos demandes et réclamations apparaîtront ici avec leur statut.":
    "Your requests and complaints will appear here with their status.",

  // ---- dashboard
  "Réclamations et demandes reçues, et leur traitement.": "Complaints and requests received, and how they are handled.",
  "Réclamations et demandes reçues, et leur traitement. Données actualisées à {time}.":
    "Complaints and requests received, and how they are handled. Data refreshed at {time}.",
  "Période": "Period",
  "7 j": "7 d",
  "30 j": "30 d",
  "90 j": "90 d",
  "Actualiser": "Refresh",
  "Actualisation impossible": "Refresh failed",
  "Impossible de charger les tickets": "Tickets could not be loaded",
  "Tickets reçus": "Tickets received",
  "dont {n} demandes": "including {n} requests",
  "{delta} vs {n} j précédents": "{delta} vs previous {n} d",
  "Ouvertes": "Open",
  "En attente de prise en charge": "Waiting to be picked up",
  "En traitement": "Being handled",
  "Résolues": "Resolved",
  "Taux de résolution {rate}": "Resolution rate {rate}",
  "Urgence haute à traiter": "High urgency to handle",
  "Non résolues": "Not resolved",
  "Les demandes et réclamations envoyées depuis l'assistant client apparaîtront ici.":
    "Requests and complaints sent from the client assistant will appear here.",
  "Volume de tickets": "Ticket volume",
  "Nombre de tickets reçus, {n} derniers jours": "Tickets received, last {n} days",
  "Nombre de tickets reçus, depuis le premier ticket": "Tickets received, since the first ticket",
  "Semaine du {day}": "Week of {day}",
  "{n} ticket": "{n} ticket",
  "{n} tickets": "{n} tickets",
  "Aucun ticket sur cette période.": "No tickets in this period.",
  "Par département": "By department",
  "Cliquez sur un département pour filtrer la liste": "Click a department to filter the list",
  "Aucune donnée.": "No data.",
  "Urgence (réclamations)": "Urgency (complaints)",
  "Filtrer par statut": "Filter by status",
  "Rechercher un ticket, un motif…": "Search tickets, issues…",
  "Rechercher dans les tickets": "Search tickets",
  "Type : tous": "Type: all",
  "Type :": "Type:",
  "Urgence : toutes": "Urgency: all",
  "Urgence :": "Urgency:",
  "Sentiment : tous": "Sentiment: all",
  "Sentiment :": "Sentiment:",
  "Département : tous": "Department: all",
  "Réinitialiser": "Reset",
  "Réinitialiser les filtres": "Reset filters",
  "Exporter CSV": "Export CSV",
  "Aucun ticket ne correspond": "No matching tickets",
  "Modifiez la période ou les filtres pour élargir la recherche.": "Change the period or filters to widen the search.",
  "{from}–{to} sur {total}": "{from}–{to} of {total}",
  "Page précédente": "Previous page",
  "Page suivante": "Next page",

  // ---- ticket panel
  "Ticket PDF": "Ticket PDF",
  "Statut du ticket": "Ticket status",
  "Ticket #{id} : {status}.": "Ticket #{id}: {status}.",
  "Statut modifié le {date} par {user}.": "Status changed on {date} by {user}.",
  "Statut modifié le {date}.": "Status changed on {date}.",
  "Réclamation du client": "Client complaint",
  "Demande du client": "Client request",
  "Réponse automatique envoyée": "Automatic reply sent",
  "Routage et notification": "Routing and notification",
  "Destinataires": "Recipients",
  "Envoyé": "Sent",
  "Non envoyé": "Not sent",
  "Classification": "Classification",
  "Mode": "Mode",
  "Tri du message": "Message triage",
  "Décision": "Decision",
  "Accord ML / LLM": "ML / LLM agreement",
  "Poids ML": "ML weight",
  "Seuil de confiance ML": "ML confidence threshold",
  "Régression logistique (TF-IDF)": "Logistic regression (TF-IDF)",
  "Motif prédit :": "Predicted issue:",
  "Modèle de langage (LLM)": "Language model (LLM)",
  "Classification LLM indisponible, repli sur le modèle local": "LLM classification unavailable, local model used instead",
  "Réponse générée localement": "Reply generated locally",
  "Contexte documentaire (RAG)": "Document context (RAG)",
  "{n} extrait utilisé pour la réponse": "{n} passage used for the reply",
  "{n} extraits utilisés pour la réponse": "{n} passages used for the reply",

  // ---- root cause analysis
  "Regroupe les tickets par motif et par département, puis explique la cause probable de chaque motif récurrent à partir du texte réel des réclamations.":
    "Groups tickets by issue and department, then explains the likely cause of each recurring pattern from the actual complaint text.",
  "Paramètres de l'analyse": "Analysis parameters",
  "Réclamations minimum par motif": "Minimum complaints per pattern",
  "Un motif n'est analysé qu'à partir de ce nombre de tickets.": "A pattern is only analysed from this number of tickets.",
  "Nombre maximum de motifs": "Maximum number of patterns",
  "Les motifs les plus fréquents sont analysés en premier.": "The most frequent patterns are analysed first.",
  "Diminuer : {label}": "Decrease: {label}",
  "Augmenter : {label}": "Increase: {label}",
  "Analyse en cours…": "Analysing…",
  "Lancer l'analyse": "Run analysis",
  "Motifs concernés": "Patterns covered",
  "{tickets} réclamations · {eligible} motifs récurrents sur {groups}":
    "{tickets} complaints · {eligible} recurring patterns out of {groups}",
  "Autres motifs au-delà du maximum choisi : {n}.": "Other patterns beyond the chosen maximum: {n}.",
  "Aucun motif n'atteint {n} réclamations. Abaissez le seuil ou attendez davantage de tickets.":
    "No pattern reaches {n} complaints. Lower the threshold or wait for more tickets.",
  "Aucune analyse lancée": "No analysis run yet",
  "Réglez les paramètres puis lancez l'analyse. Le rapport s'affiche ici et peut être exporté en PDF.":
    "Set the parameters, then run the analysis. The report appears here and can be exported as a PDF.",
  "Synthèse": "Summary",
  "Analyse du {date} · seuil {min}, {max} motifs maximum": "Analysis of {date} · threshold {min}, up to {max} patterns",
  "Rapport PDF": "PDF report",
  "Aucun motif n'a atteint le seuil minimum pour cette analyse.": "No pattern reached the minimum threshold for this analysis.",
  "{n} réclamation": "{n} complaint",
  "{n} réclamations": "{n} complaints",
  "Cause racine probable": "Likely root cause",
  "Éléments à l'appui": "Supporting evidence",
  "Action recommandée": "Recommended action",

  // ---- settings: tabs & AI engine
  "Configuration de l'agent, des notifications et des accès. Réservé aux administrateurs.":
    "Agent, notification and access configuration. Administrators only.",
  "Moteur IA": "AI engine",
  "E-mails et routage": "E-mail and routing",
  "Comptes et rôles": "Accounts and roles",
  "Base de connaissances": "Knowledge base",
  "Configuration indisponible": "Configuration unavailable",
  "Configuration du moteur IA enregistrée.": "AI engine configuration saved.",
  "Modèle local ré-entraîné.": "Local model retrained.",
  "Classification des réclamations": "Complaint classification",
  "Arbitrage entre le modèle local (TF-IDF + régression logistique) et le modèle de langage.":
    "Arbitration between the local model (TF-IDF + logistic regression) and the language model.",
  "Mode de classification": "Classification mode",
  "Hybride": "Hybrid",
  "ML + LLM": "ML + LLM",
  "Modèle de langage (Gemini)": "Language model (Gemini)",
  "Régression logistique": "Logistic regression",
  "Les deux modèles classent la réclamation ; un arbitrage tranche en cas de désaccord.":
    "Both models classify the complaint; arbitration settles any disagreement.",
  "Le modèle de langage décide seul du département et du motif.": "The language model alone decides the department and issue.",
  "Classification locale, sans appel au modèle de langage.": "Local classification, without calling the language model.",
  "Poids du modèle local (ML) face au LLM": "Local model (ML) weight versus the LLM",
  "Seuil de confiance du modèle local (LR)": "Local model (LR) confidence threshold",
  "0 % · priorité LLM": "0% · LLM first",
  "50 %": "50%",
  "100 % · priorité ML": "100% · ML first",
  "40 %": "40%",
  "95 %": "95%",
  "Le poids et le seuil ne s'appliquent qu'en mode hybride.": "Weight and threshold only apply in hybrid mode.",
  "En cas de désaccord, le modèle local l'emporte lorsque sa confiance atteint {threshold} ; sinon le LLM décide.":
    "When the models disagree, the local model wins once its confidence reaches {threshold}; otherwise the LLM decides.",
  "Avec un poids de 50 % ou moins, le LLM l'emporte toujours en cas de désaccord. Passez au-dessus de 50 % pour que le seuil de confiance s'applique.":
    "With a weight of 50% or less, the LLM always wins a disagreement. Go above 50% for the confidence threshold to apply.",
  "Modèle de langage": "Language model",
  "Identifiant du modèle Gemini utilisé pour la classification.": "Identifier of the Gemini model used for classification.",
  "Modifications non enregistrées": "Unsaved changes",
  "Modèle local": "Local model",
  "Ré-entraîne la régression logistique sur le jeu d'exemples initial et sur l'historique des tickets.":
    "Retrains the logistic regression on the seed examples and the ticket history.",
  "Entraînement…": "Training…",
  "Ré-entraîner": "Retrain",
  "Réclamations utilisées": "Complaints used",
  "Départements reconnus": "Departments recognised",
  "Lancez un ré-entraînement après avoir accumulé de nouveaux tickets pour que le modèle local en tienne compte.":
    "Retrain after new tickets have accumulated so the local model takes them into account.",

  // ---- settings: e-mail
  "Configuration e-mail indisponible": "E-mail configuration unavailable",
  "Configuration SMTP enregistrée.": "SMTP configuration saved.",
  "Serveur d'envoi (SMTP)": "Outgoing server (SMTP)",
  "À chaque ticket, le PDF est envoyé aux destinataires du département concerné.":
    "For each ticket, the PDF is sent to the recipients of the department concerned.",
  "Envoi actif": "Sending active",
  "Identifiants manquants": "Credentials missing",
  "Envoi désactivé": "Sending disabled",
  "Activer l'envoi des e-mails": "Enable e-mail sending",
  "Désactivé, les tickets sont créés sans notification.": "When disabled, tickets are created without notification.",
  "Serveur": "Server",
  "Port": "Port",
  "Port invalide": "Invalid port",
  "Laissez vide pour conserver le mot de passe actuel.": "Leave empty to keep the current password.",
  "Pour Gmail : mot de passe d'application (16 caractères).": "For Gmail: app password (16 characters).",
  "•••••••• (enregistré)": "•••••••• (saved)",
  "adresse@domaine.com": "address@domain.com",
  "Expéditeur affiché": "Displayed sender",
  "Exemple : ECCBC Service Client <adresse@domaine.com>": "Example: ECCBC Customer Desk <address@domain.com>",
  "Chiffrement STARTTLS": "STARTTLS encryption",
  "Recommandé sur le port 587. Le port 465 utilise SSL automatiquement.":
    "Recommended on port 587. Port 465 uses SSL automatically.",
  "Tester l'envoi": "Test sending",
  "Envoie un message de vérification avec la configuration enregistrée.":
    "Sends a verification message using the saved configuration.",
  "Adresse de destination": "Recipient address",
  "vous@domaine.com": "you@domain.com",
  "Envoi…": "Sending…",
  "Envoyer un e-mail de test": "Send a test e-mail",
  "Destinataires par département": "Recipients by department",
  "Personnes notifiées, avec le ticket PDF en pièce jointe, selon le département retenu par la classification.":
    "People notified, with the ticket PDF attached, according to the department chosen by the classification.",
  "Aucun destinataire.": "No recipients.",
  "Adresse d'exemple, ignorée à l'envoi": "Placeholder address, skipped when sending",
  "nouvelle.adresse@…": "new.address@…",
  "{email} ajouté.": "{email} added.",
  "{email} retiré.": "{email} removed.",
  "Retirer {email}": "Remove {email}",
  "Ajouter un destinataire pour {name}": "Add a recipient for {name}",
  "Retirer ce destinataire ?": "Remove this recipient?",
  "{email} ne recevra plus les notifications du département « {name} ».":
    "{email} will no longer receive notifications for the “{name}” department.",

  // ---- settings: accounts
  "Comptes indisponibles": "Accounts unavailable",
  "Filtrer par rôle": "Filter by role",
  "Rechercher un compte…": "Search accounts…",
  "Rechercher un compte": "Search accounts",
  "Nouveau compte": "New account",
  "Aucun compte ne correspond": "No matching accounts",
  "Modifiez le filtre ou la recherche.": "Change the filter or the search.",
  "Dernière connexion {when}": "Last sign-in {when}",
  "Jamais connecté": "Never signed in",
  "Désactivé": "Disabled",
  "Modifier {name}": "Edit {name}",
  "Supprimer {name}": "Delete {name}",
  "Droits par rôle": "Permissions by role",
  "Les mêmes règles sont appliquées par l'API, quel que soit l'écran affiché.":
    "The API enforces the same rules, whatever screen is shown.",
  "Écran": "Screen",
  "Autorisé": "Allowed",
  "Non autorisé": "Not allowed",
  "Supprimer ce compte ?": "Delete this account?",
  "Le compte « {username} » ({name}) ne pourra plus se connecter. Ses tickets sont conservés.":
    "The account “{username}” ({name}) will no longer be able to sign in. Its tickets are kept.",
  "Compte « {name} » supprimé.": "Account “{name}” deleted.",
  "Compte « {name} » créé.": "Account “{name}” created.",
  "Compte « {name} » mis à jour.": "Account “{name}” updated.",
  "Le compte est utilisable dès sa création.": "The account can be used as soon as it is created.",
  "Créer le compte": "Create account",
  "Rôle": "Role",
  "Vous ne pouvez pas modifier votre propre rôle.": "You cannot change your own role.",
  "Nom complet": "Full name",
  "3 caractères minimum, sans espace.": "At least 3 characters, no spaces.",
  "Non modifiable.": "Cannot be changed.",
  "Point de vente / société": "Outlet / company",
  "Service": "Department",
  "E-mail (facultatif)": "E-mail (optional)",
  "8 caractères minimum. Communiquez-le à l'utilisateur.": "At least 8 characters. Share it with the user.",
  "Laissez vide pour ne pas le changer.": "Leave empty to keep it unchanged.",
  "Générer": "Generate",
  "Compte actif": "Active account",
  "Vous ne pouvez pas désactiver votre propre compte.": "You cannot disable your own account.",
  "Un compte désactivé ne peut plus se connecter.": "A disabled account can no longer sign in.",

  // ---- settings: knowledge base
  "Base de connaissances indisponible": "Knowledge base unavailable",
  "Ajouter des documents": "Add documents",
  "Les documents ajoutés sont indexés immédiatement et utilisés par l'assistant pour répondre.":
    "Added documents are indexed immediately and used by the assistant to answer.",
  "Glissez vos fichiers ici": "Drop your files here",
  "PDF, Word (.docx), TXT, Markdown ou CSV · {max} maximum par fichier": "PDF, Word (.docx), TXT, Markdown or CSV · up to {max} per file",
  "Choisir des fichiers": "Choose files",
  "Envoi et indexation…": "Uploading and indexing…",
  "Format non pris en charge.": "Unsupported format.",
  "Fichier trop volumineux (maximum {max}).": "File too large (maximum {max}).",
  "Ajouté": "Added",
  "Remplacé": "Replaced",
  "Documents de référence": "Reference documents",
  "Sources lues par l'assistant pour rédiger ses réponses.": "Sources the assistant reads to write its replies.",
  "Indexation…": "Indexing…",
  "Reconstruire l'index": "Rebuild index",
  "Index reconstruit : {n} fragments indexés.": "Index rebuilt: {n} chunks indexed.",
  "fragment indexé": "chunk indexed",
  "fragments indexés": "chunks indexed",
  "reconstruisez l'index pour activer la recherche documentaire": "rebuild the index to enable document search",
  "Aucun document": "No documents",
  "Ajoutez un premier document ci-dessus.": "Add a first document above.",
  "Document inclus dans le déploiement, non supprimable ici": "Document shipped with the deployment, cannot be deleted here",
  "Supprimer ce document ?": "Delete this document?",
  "« {name} » sera supprimé du serveur et l'assistant ne s'en servira plus.":
    "“{name}” will be deleted from the server and the assistant will stop using it.",
  "« {name} » supprimé de la base.": "“{name}” deleted from the knowledge base.",

  // ---- messages returned by the API
  "Identifiant ou mot de passe incorrect.": "Incorrect username or password.",
  "Authentification requise.": "Authentication required.",
  "Session expirée ou invalide.": "Session expired or invalid.",
  "Compte désactivé ou supprimé.": "Account disabled or deleted.",
  "Accès refusé pour ce rôle.": "Access denied for this role.",
  "Le nom est obligatoire.": "Name is required.",
  "Mot de passe actuel incorrect.": "Current password is incorrect.",
  "Le mot de passe doit contenir au moins 8 caractères.": "The password must be at least 8 characters long.",
  "Identifiant invalide : 3 caractères minimum, lettres, chiffres, point, tiret ou underscore.":
    "Invalid username: at least 3 characters; letters, digits, dot, hyphen or underscore.",
  "Au moins un administrateur actif est requis.": "At least one active administrator is required.",
  "Vous ne pouvez pas supprimer votre propre compte.": "You cannot delete your own account.",
  "Vous ne pouvez pas retirer vos propres droits d'administrateur.": "You cannot remove your own administrator rights.",
  "Compte introuvable.": "Account not found.",
  "Ticket introuvable.": "Ticket not found.",
  "Adresse e-mail invalide.": "Invalid e-mail address.",
  "Port SMTP invalide.": "Invalid SMTP port.",
  "Nom de fichier invalide.": "Invalid file name.",
  "Format non pris en charge. Formats acceptés : PDF, DOCX, TXT, MD, CSV.":
    "Unsupported format. Accepted formats: PDF, DOCX, TXT, MD, CSV.",
  "Le fichier est vide.": "The file is empty.",
  "Aucun texte lisible dans ce fichier (document corrompu ou numérisé en image).":
    "No readable text in this file (corrupt document or scanned as an image).",
  "Ce document fait partie du déploiement et ne peut pas être supprimé ici.":
    "This document is part of the deployment and cannot be deleted here.",
  "Document introuvable.": "Document not found.",
};
